name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

    - name: Install dependencies
      run: mix deps.get

    - name: Run Credo
      run: mix credo --strict
    
    - name: Check format
      run: mix format --check-formatted

    - name: Run Tests
      run: mix test
